/**
 * Audit action enumeration
 *
 * Defines all auditable actions in the system (T159-T169)
 */
export enum AuditAction {
  // Bet actions
  BET_PLACED = 'BET_PLACED',
  BET_CANCELLED = 'BET_CANCELLED',
  BET_WON = 'BET_WON',
  BET_LOST = 'BET_LOST',

  // Agent/User actions
  AGENT_CREATED = 'AGENT_CREATED',
  AGENT_UPDATED = 'AGENT_UPDATED',
  AGENT_DELETED = 'AGENT_DELETED',
  USER_LOGIN = 'USER_LOGIN',
  USER_LOGOUT = 'USER_LOGOUT',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  PASSWORD_RESET = 'PASSWORD_RESET',

  // Limit actions
  LIMIT_ADJUSTED = 'LIMIT_ADJUSTED',
  WEEKLY_LIMIT_RESET = 'WEEKLY_LIMIT_RESET',
  LIMIT_EXCEEDED = 'LIMIT_EXCEEDED',

  // Result actions
  RESULT_SYNCED = 'RESULT_SYNCED',
  RESULT_MANUAL_ENTRY = 'RESULT_MANUAL_ENTRY',
  RESULT_UPDATED = 'RESULT_UPDATED',
  RESULT_PROCESSED = 'RESULT_PROCESSED',

  // Commission actions
  COMMISSION_CALCULATED = 'COMMISSION_CALCULATED',
  COMMISSION_ADJUSTED = 'COMMISSION_ADJUSTED',

  // Provider actions
  PROVIDER_CREATED = 'PROVIDER_CREATED',
  PROVIDER_UPDATED = 'PROVIDER_UPDATED',
  PROVIDER_DELETED = 'PROVIDER_DELETED',

  // System actions
  SYSTEM_ERROR = 'SYSTEM_ERROR',
  SYSTEM_WARNING = 'SYSTEM_WARNING',
}
